import MainLayout from "./components/Layout/MainLayout";
import MenuContextProvider from "./context/MenuContext";
import "./globals.css";

export const metadata = {
  title: "Inventory Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <MenuContextProvider>
        <MainLayout>{children}</MainLayout>
        </MenuContextProvider>
        
      </body>
    </html>
  );
}
