import Sidebar from "../components/common/Sidebar";
import MenuContextProvider from "../components/common/MenuContext";
import "./globals.css";

export const metadata = {
  title: "Inventory Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <MenuContextProvider>
        <Sidebar>{children}</Sidebar>
        </MenuContextProvider>
        
      </body>
    </html>
  );
}
